// domain
export const DOMAIN = "https://c43658a3a90b.ngrok.io";
// export const DOMAIN = "https://f32531d8ff9a.ngrok.io";
export const LIMIT = 10;

// HTTP method 
export const HTTP_READ = "GET"
export const HTTP_CREATE = "POST"
export const HTTP_UPDATE = "PUT"
export const HTTP_DELETE = "DELETE"

// HTTP headers
export const HTTP_HEADER_JSON = {"Content-Type": "Application/json"}

// types of actions
export const GET_SCHEDULES_REQUEST = "GET_SCHEDULES_REQUEST";
export const GET_SCHEDULES_SUCCESS = "GET_SCHEDULES_SUCCESS";
export const GET_SCHEDULES_FAIL    = "GET_SCHEDULES_FAIL";

export const GET_CRITERIA_REQUEST = "GET_CRITERIA_REQUEST";
export const GET_CRITERIA_SUCCESS = "GET_CRITERIA_SUCCESS";
export const GET_CRITERIA_FAIL    = "GET_CRITERIA_FAIL";

export const CREATE_SCHEDULES_REQUEST = "CREATE_SCHEDULES_REQUEST";
export const CREATE_SCHEDULES_SUCCESS = "CREATE_SCHEDULES_SUCCESS";
export const CREATE_SCHEDULES_FAIL    = "CREATE_SCHEDULES_FAIL";

export const UPDATE_SCHEDULES_REQUEST = "UPDATE_SCHEDULES_REQUEST";
export const UPDATE_SCHEDULES_SUCCESS = "UPDATE_SCHEDULES_SUCCESS";
export const UPDATE_SCHEDULES_FAIL    = "UPDATE_SCHEDULES_FAIL";

export const DELETE_SCHEDULES_REQUEST = "DELETE_SCHEDULES_REQUEST";
export const DELETE_SCHEDULES_SUCCESS = "DELETE_SCHEDULES_SUCCESS";
export const DELETE_SCHEDULES_FAIL    = "DELETE_SCHEDULES_FAIL";

export const CREATE_CRITERIA_REQUEST = "CREATE_CRITERIA_REQUEST";
export const CREATE_CRITERIA_SUCCESS = "CREATE_CRITERIA_SUCCESS";
export const CREATE_CRITERIA_FAIL    = "CREATE_CRITERIA_FAIL";

export const UPDATE_CRITERIA_REQUEST = "UPDATE_CRITERIA_REQUEST";
export const UPDATE_CRITERIA_SUCCESS = "UPDATE_CRITERIA_SUCCESS";
export const UPDATE_CRITERIA_FAIL    = "UPDATE_CRITERIA_FAIL";

export const DELETE_CRITERIA_REQUEST = "DELETE_CRITERIA_REQUEST";
export const DELETE_CRITERIA_SUCCESS = "DELETE_CRITERIA_SUCCESS";
export const DELETE_CRITERIA_FAIL    = "DELETE_CRITERIA_FAIL";

export const GET_ALL_CRITERIA_REQUEST = "GET_ALL_CRITERIA_REQUEST";
export const GET_ALL_CRITERIA_SUCCESS = "GET_ALL_CRITERIA_SUCCESS";
export const GET_ALL_CRITERIA_FAIL    = "GET_ALL_CRITERIA_FAIL";

export const GET_ALL_SCHEDULE_REQUEST = "GET_ALL_SCHEDULE_REQUEST";
export const GET_ALL_SCHEDULE_SUCCESS = "GET_ALL_SCHEDULE_SUCCESS";
export const GET_ALL_SCHEDULE_FAIL    = "GET_ALL_SCHEDULE_FAIL";

export const CHOOSE_CRITERIA   = "CHOOSE_CRITERIA";
export const UNCHOOSE_CRITERIA = "UNCHOOSE_CRITERIA";

export const CHOOSE_SCHEDULE  = "CHOOSE_SCHEDULE";
export const UNCHOOSE_SCHEDULE = "UNCHOOSE_SCHEDULE";

export const SET_LIST_VIEW_CRITERIA = "SET_LIST_VIEW_CRITERIA";

export const SET_LIST_VIEW_SCHEDULE = "SET_LIST_VIEW_SCHEDULE";

export const GET_ALL_QUIZ_REQUEST = "GET_ALL_QUIZ_REQUEST";
export const GET_ALL_QUIZ_SUCCESS = "GET_ALL_QUIZ_SUCCESS";
export const GET_ALL_QUIZ_FAIL    = "GET_ALL_QUIZ_FAIL";

export const CREATE_QUIZ_REQUEST = "CREATE_QUIZ_REQUEST";
export const CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS";
export const CREATE_QUIZ_FAIL    = "CREATE_QUIZ_FAIL";

export const UPDATE_QUIZ_REQUEST = "UPDATE_QUIZ_REQUEST";
export const UPDATE_QUIZ_SUCCESS = "UPDATE_QUIZ_SUCCESS";
export const UPDATE_QUIZ_FAIL    = "UPDATE_QUIZ_FAIL";

export const DELETE_QUIZ_REQUEST = "DELETE_QUIZ_REQUEST";
export const DELETE_QUIZ_SUCCESS = "DELETE_QUIZ_SUCCESS";
export const DELETE_QUIZ_FAIL    = "DELETE_QUIZ_FAIL";

